# Following
# https://github.com/SUSE/style-guides/blob/master/Ruby.md

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Is there any justification for "aligned" which is the default?
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#arrays
Style/WordArray:
  Enabled: false

# force for array of symbols plain array
Style/SymbolArray:
  EnforcedStyle: brackets

# align arrows:
# "foo"     => true
# "foo_bar" => false
# and also colons:
# foo:     true
# foo_bar: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# no extra indentation for multiline function calls
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# no extra indentation for case
Layout/CaseIndentation:
  EnforcedStyle: end

# "unless" has a different connotation than "if not"
Style/NegatedIf:
  Enabled: false

# use "raise" instead of "fail"
Style/SignalException:
  EnforcedStyle: only_raise

# do not force %r
Style/RegexpLiteral:
  Enabled: false

# Easier recognization if access modified used
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
